### ISSUE TITLE
Issues using Scout after setting up SSL on Elasticsearch

### ISSUE THREAD

**Issue by encompassJeff** [babenkoivan/elastic-client#1]
| Software        | Version
| ------------- | ---------------
| PHP                | 7.3
| Elasticsearch | 7.8.1

**Describe the issue**
Sorry, maybe this falls in-between a bug and a feature request, but I am stuck with my configurations. 

I previously had set up `elastic-migrations`, `elastic-scout-driver`, and `elastic-scout-driver-plus` on my local machine to power search in our application through Elastic. I successfully followed the documentation here and in ElasticSearch to set up a connection that uses `user/pass` authentication and everything was working great over http. However, after setting up ElasticSearch SSL/TLS on a public environment to secure the stack, I can no longer use the Scout drivers no matter how I adjust the configuration.

I am using the ELK stack as configured in Laradock (with some adjustments) and previously, my working `hosts` value for the `elastic.client.config` file was `http://username:password@elasticsearch:9200` (elasticsearch:9200 is my container `elasticsearch` running on the host machine). This was working well with excellent performance! I deployed it to a public testing environment and had great success with it. But we had to set up SSL for additional security, especially because we are using Kibana. Upon setting the SSL/TLS configs for the `elasticsearch` docker container, the Scout driver packages no longer work suddenly.

I assumed it was an issue with host and I have tried to modify the `hosts` in `elastic.client.config` to connect via https instead: `https://username:password@elasticsearch:9200` but always receive the message back that there are `No alive nodes found in your cluster`. However when I run the curl `GET _cat/nodes` I can see that there are nodes alive. I have tried many different configuration settings in the `elastic.client.config` file but always getting the same response about no alive nodes. I've tried passing the paths to the SSL certificates inside config file, I've tried changing the format of the config file to other formats based on ElasticSearch documentation, but still no success.

If you can provide any insight into how I can configure my elastic client to connect via https for these packages, I would appreciate it greatly!

**Comment by babenkoivan** [comment]
Hi @encompassJeff, Elastic Client is just an adapter for https://github.com/elastic/elasticsearch-php. It uses [ClientBuilder::fromConfig](https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/configuration.html#_building_the_client_from_a_configuration_hash) to create a client instance, which means you can use any configuration options supported by `elasticsearch-php` in the config file.

There is an example [here](https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/configuration.html#_extended_host_configuration), which looks relevant to your case:

```php
return [
    'hosts' => [
        // This is effectively equal to: "https://username:password!#$?*abc@foo.com:9200/elastic"
        [
            'host' => 'foo.com',
            'port' => '9200',
            'scheme' => 'https',
            'path' => '/elastic',
            'user' => 'username',
            'pass' => 'password!#$?*abc'
        ]
    ]
];
```

Do you run `GET _cat/nodes` from the server or locally? Do you use the same port? 
It should work, I think you just missing something..

**Comment by encompassJeff** [comment]
Hi @babenkoivan thanks very much for the reply! 

As you suggested, it just took time to find the right missing config settings. I needed to set up an additional option on the config file, `sslVerification=>false`, and it worked.
