### ISSUE TITLE
No alive nodes found in your cluster

### ISSUE THREAD

**Issue by tcagkansokmen** [babenkoivan/elastic-client#5]
| Software        | Version
| ------------- | ---------------
| PHP                | 7.4

my config/elastic.client.php file 
<?php declare(strict_types=1);

return [
    'hosts' => [
        [
            'host' => 'https://blabla-central1.gcp.cloud.es.io',
            'port' => '9200',
            'user' => 'xxxx',
            'pass' => 'xxxxx'
        ]
    ]
];

when I try to connect (i am using scout) it returns.
Whats wrong with it? How can I connect to elastic.co server?

""message": "No alive nodes found in your cluster",
    "exception": "Elasticsearch\\Common\\Exceptions\\NoNodesAvailableException",
    "file": "/Users/tufancagkansokmen/Valet/bkm-admin/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php",
    "line": 64,"

**Comment by babenkoivan** [comment]
Hi @tcagkansokmen, I doubt it is a bug in Elastic Client, cause this library just a wrapper for `elasticsearch/elasticsearch`. I think you need to check your connection parameters, maybe you should use `http` instead of `https`, or verify that `user/pass` are correct.

**Comment by mofolo** [comment]
The easiest way to fix this is to bake in the username/password into the endpoint URL.
This is the credentials generated when creating the instance: 

For example:
`ELASTIC_HOST=https://username:password@endpoint.aws.found.io:1234`

**Comment by jesseckwon** [comment]
> The easiest way to fix this is to bake in the username/password into the endpoint URL. This is the credentials generated when creating the instance:
> 
> For example: `ELASTIC_HOST=https://username:password@endpoint.aws.found.io:1234`

When I try this 
Response:
`  401 Unauthorized: {"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/my_index]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","ApiKey"]}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/my_index]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","ApiKey"]}},"status":401}`

And then, I debug and found solution
> config/elastic.client.php
```php
<?php declare(strict_types=1);

return [
    'default' => env('ELASTIC_CONNECTION', 'default'),
    'connections' => [
        'default' => [
            'hosts' => [
                env('ELASTIC_HOST', 'localhost:9200'),
            ],
            'basicAuthentication' => [
                env('ELASTIC_USERNAME', 'elastic'),
                env('ELASTIC_PASSWORD', 'ELASTIC_PASSWORD'),
            ],
        ],
    ],
];

```

**Comment by mofolo** [comment]
Thanks, correct that solution doesn't work anymore.
If you're using the Elastic Cloud you can use Cloud_ID and API_Key which is found off the Cloud console to make the connection

`config/elastic.client.php`

```
return [
    'default' => env('ELASTIC_CONNECTION', 'default'),
    'cloud_id'  =>  env('ELASTIC_CLOUD_ID', ''),
    'api_key'   =>  env('ELASTIC_API_KEY', ''),
    'connections' => [
        'default' => [
            'hosts' => [
                env('ELASTIC_HOST', 'localhost:9200'),
                ],
            ]
        ],
];
```

**Comment by jesseckwon** [comment]
Oh, thank you very much.
I think I should use .env to control it.
```ini
ELASTIC_CONNECTION=development
ELASTIC_CONNECTION=production
```

`config/elastic.client.php`
```php
<?php declare(strict_types=1);

return [
    'default' => env('ELASTIC_CONNECTION', 'production'),
    'connections' => [
        'production' => [
            'hosts' => [
                env('ELASTIC_HOST', 'localhost:9200'),
            ],
        ],
        'development' => [
            'hosts' => [
                env('ELASTIC_HOST', 'localhost:9200'),
            ],
            'basicAuthentication' => [
                env('ELASTIC_USERNAME', 'elastic'),
                env('ELASTIC_PASSWORD', 'ELASTIC_PASSWORD'),
            ],
        ],
    ],
];

```

Thank you again.

**Comment by StewartJ-SSG** [comment]
@babenkoivan - could this be added to the docs? I spent a few days trying to get this working until I decided to search closed issues here.

**Comment by babenkoivan** [comment]
@StewartJ-SSG I've updated the README file.
